//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmisSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties_Resources_tlh_KX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties_Resources_tlh_KX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmisSync.Properties.Resources.tlh-KX", typeof(Properties_Resources_tlh_KX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chel.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; Hop chel.
        /// </summary>
        internal static string AddARemoteFolder {
            get {
                return ResourceManager.GetString("AddARemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSyncDaq ngaSwI&apos;lIj rapmoHlu&apos;bogh chellI&apos;.
        /// </summary>
        internal static string AddFolders {
            get {
                return ResourceManager.GetString("AddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; chellI&apos;.
        /// </summary>
        internal static string AddingFolder {
            get {
                return ResourceManager.GetString("AddingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoH.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; Hop legh.
        /// </summary>
        internal static string BrowseRemoteFolder {
            get {
                return ResourceManager.GetString("BrowseRemoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qIl.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polmeH janvamDaq De&apos; Quv choH:.
        /// </summary>
        internal static string ChangeRepoPath {
            get {
                return ResourceManager.GetString("ChangeRepoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navmey rapmoHlu&apos;bogh De&apos;wI&apos;lIjDaq ngaswI&apos; le&apos; chenmoH CmisSync..
        /// </summary>
        internal static string CmisSyncCreates {
            get {
                return ResourceManager.GetString("CmisSyncCreates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taH.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; Sum pong choH.
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to juplI&apos;vo&apos; Hevbogh choHmey SuqmeH navmey chu&apos;moH, &apos;ej tebwI&apos;Daq je choHmeylIj ngeH je..
        /// </summary>
        internal static string DocumentsAre {
            get {
                return ResourceManager.GetString("DocumentsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL chIm.
        /// </summary>
        internal static string EmptyURLNotAllowed {
            get {
                return ResourceManager.GetString("EmptyURLNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De&apos;wI&apos; SumDaq navmey rapmoHlu&apos;bogh ngaSwI&apos;&apos;e&apos; yIpong.
        /// </summary>
        internal static string EnterLocalFolderName {
            get {
                return ResourceManager.GetString("EnterLocalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navmey leghlu&apos;bogh weQmoQnaQ Quv&apos;e&apos; yIghItlh:.
        /// </summary>
        internal static string EnterWebAddress {
            get {
                return ResourceManager.GetString("EnterWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chu&apos;Ha&apos;.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choHmey ngeHlaHbe&apos;.
        /// </summary>
        internal static string FailedToSendSomeChanges {
            get {
                return ResourceManager.GetString("FailedToSendSomeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navmey chu&apos;moH.
        /// </summary>
        internal static string FilesUpToDate {
            get {
                return ResourceManager.GetString("FilesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rInmoH.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync ngaSwI&apos;&apos;a&apos;Daq ngaSwI&apos; tu&apos;lu&apos;pu&apos;.
        /// </summary>
        internal static string FolderAlreadyExist {
            get {
                return ResourceManager.GetString("FolderAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QaH.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rarbe&apos;DI&apos; CMIS lobbogh &apos;entepray&apos; tebwI&apos;Daq rapmoHtaH &apos;e&apos; chaw&apos; CmisSync.
        ///
        ///&apos;entepray&apos; ngaStaHghach vu&apos;meH Dropbox rur!.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lughbe&apos; ngaSwI&apos; pong. pIqaD le&apos; chaw&apos;be&apos;lu&apos;..
        /// </summary>
        internal static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qapbe&apos;bogh URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; Sum pongvetlh tu&apos;lu&apos;, pong pIm yIpong..
        /// </summary>
        internal static string LocalDirectoryExist {
            get {
                return ResourceManager.GetString("LocalDirectoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tInchugh ngaSwI&apos; &apos;ut poH nI&apos;..
        /// </summary>
        internal static string MayTakeTime {
            get {
                return ResourceManager.GetString("MayTakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; rapmoHlu&apos;bogh poSmoH.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngaSwI&apos; Sum poSmoH.
        /// </summary>
        internal static string OpenLocalFolder {
            get {
                return ResourceManager.GetString("OpenLocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pegh mu&apos;.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rapmoH &apos;e&apos; yImev.
        /// </summary>
        internal static string PauseSync {
            get {
                return ResourceManager.GetString("PauseSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMIS De&apos;wI&apos;&apos;a&apos; tu&apos;lu&apos;, &apos;ach naw&apos; chaw&apos;be&apos;lu&apos;. lo&apos;wI&apos; pong pegh mu&apos; je yInuD..
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaH navmeylIj rapmoHlI&apos;.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choHmey HevlI&apos;….
        /// </summary>
        internal static string ReceivingChanges {
            get {
                return ResourceManager.GetString("ReceivingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rapqa&apos;moH.
        /// </summary>
        internal static string ResumeSync {
            get {
                return ResourceManager.GetString("ResumeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choHmey ngeHlI&apos;.
        /// </summary>
        internal static string SendingChanges {
            get {
                return ResourceManager.GetString("SendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevmeH mIw buSHa&apos;.
        /// </summary>
        internal static string SkipTutorial {
            get {
                return ResourceManager.GetString("SkipTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pIQoS, QuvvamDaq CMIS De&apos;wI&apos;&apos;a&apos; tu&apos;laHbe&apos; CmisSync. yInuDqa&apos;.
        ///lughchugh Quvvam, chIjwI&apos;Daq yIpoSmoH &apos;ej CmisSync vaSDaq XMLvetlh yIngeH..
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chu&apos;meH tetlhDaq CmisSync chel.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naDev DuQaHmeH Dotlh mIllogh tu&apos;lu&apos;.
        /// </summary>
        internal static string StatusIcon {
            get {
                return ResourceManager.GetString("StatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rapmoHlI&apos;bogh mIw &apos;agh CmisSync Dotlh mIllogh, &apos;ej naw&apos; ngeD chaw&apos;..
        /// </summary>
        internal static string StatusIconShows {
            get {
                return ResourceManager.GetString("StatusIconShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rapmoHghach.
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choHmey rapmoHlI&apos;….
        /// </summary>
        internal static string SyncingChanges {
            get {
                return ResourceManager.GetString("SyncingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lo&apos;wI&apos;.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pIpIH.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ghIq qaS nuq?.
        /// </summary>
        internal static string WhatsNext {
            get {
                return ResourceManager.GetString("WhatsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuqDaq &apos;oH ghomlIj De&apos;wI&apos;&apos;a&apos;?.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuqDaq Quvvam tu&apos;laH.
        /// </summary>
        internal static string WhereToFind {
            get {
                return ResourceManager.GetString("WhereToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarapmoHmeH ngaSwI&apos; Hop yIwIv.
        /// </summary>
        internal static string Which {
            get {
                return ResourceManager.GetString("Which", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochlogh CMIS ngaSwI&apos; chu&apos; chellaH..
        /// </summary>
        internal static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmisSync ngaSwI&apos;lIjDaq Datu&apos;laH..
        /// </summary>
        internal static string YouCanFind {
            get {
                return ResourceManager.GetString("YouCanFind", resourceCulture);
            }
        }
    }
}
